export const columns01 = [
  {
    "fieldName":"treeName",
    "name":"treeName",
    "width":150,
    "header":{
      "text":"지역명"
    },
    "autoFilter":true
  },
  {
    "fieldName":"treeId",
    "name":"treeId",
    "header":{
      "text":"TreeID"
    }
  },
  {
    "fieldName":"area1code",
    "name":"area1code",
    "header":{
      "text":"시도코드"
    },
    "lookupDisplay":true,
    "sortByLabel":true,
    "labelField":"area1name"
  },
  {
    "fieldName":"area1name",
    "name":"area1name",
    "header":{
      "text":"시도명"
    }
  },
  {
    "fieldName":"area2code",
    "name":"area2code",
    "header":{
      "showTooltip":true,
      "text":"시군구코드"
    }
  },
  {
    "fieldName":"area2name",
    "name":"area2name",
    "header":{
      "text":"시군구명"
    }
  },
  {
    "fieldName":"area3code",
    "name":"area3code",
    "header":{
      "text":"읍면동코드"
    }
  },
  {
    "fieldName":"area3name",
    "name":"area3name",
    "header":{
      "text":"읍면동명"
    }
  },
  {
    "fieldName":"iconField",
    "name":"iconField"
  }
];
