name: "Chromatic"
on: 
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: install dependencies 
    - run: npm install 
    - uses: deploy to chromatic 
    - run: npm run chromatic
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        